# Generated by Django 3.1.7 on 2021-02-28 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Device_name', models.TextField(max_length=50)),
                ('Location', models.TextField(default='ECC Building')),
            ],
        ),
    ]
